version: '3'

services:
  python:
    build:
      dockerfile: Dockerfile
    # command: uwsgi --socket :8001 --module config.wsgi --py-autoreload 1 --logto /tmp/uwsgi.log
    restart: unless-stopped
    container_name: Django
    volumes:
      - ./src:/code
      - ./static:/static
    ports:
      # - "80:80"
      - "3306:3306"
    # expose:
    #   - "8001"
    env_file:
      - ./src/.env.prod
